<a href="https://colab.research.google.com/github/ZielonoDziuranin/data-science/blob/main/LinAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
v1 =  np.array([-1, 4])
np.linalg.norm(v1)

4.123105625617661

In [6]:
v2 = np.array([-10, 10, -13])
np.linalg.norm(v2)

19.209372712298546

In [7]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

5.0

In [8]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

In [6]:
X = np.array([[5,3], [3, 9]])
Y = np.array([[1], [-1]])
print(Y, 'n/')
print(X)

[[ 1]
 [-1]] n/
[[5 3]
 [3 9]]


In [5]:
Z = np.dot(X, Y)
np.shape(Z)
print(Z)

[[ 2]
 [-6]]


In [7]:
np.eye(5, dtype= 'bool')

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [2]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])